version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    command: yarn start
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./yarn.lock:/app/yarn.lock
    ports:
      - "3000:3000"
    stdin_open: true
